apiVersion: v1
kind: ConfigMap
metadata:
  name: front
  namespace: default
data:
  config.js: |-
          const config = {
              "apiUrl": "http://localhost/api",
              "dateFormat": "YYYY-MM-DD",
              "dateTimeFormat": "YYYY-MM-DD HH:mm",
              "perPage": 20,
              "debug": false,
              "modules": []
          };
          window.OpenLoyaltyConfig = {
              "apiUrl": "http://localhost/api",
              "dateFormat": "YYYY-MM-DD",
              "dateTimeFormat": "YYYY-MM-DD HH:mm",
              "perPage": 20,
              "debug": false,
              "modules": []
          };
