---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-loyalty-database-pv0
  namespace: default
  labels:
    storage-tier: database
spec:
  capacity:
    storage: 20Gi
  nfs:
    server: 10.146.10.241
    path: "/nfsshared/openloyalty/database"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-loyalty-elasticsearch-pv0
  namespace: default
  labels:
    storage-tier: elasticsearch
spec:
  capacity:
    storage: 25Gi
  nfs:
    server: 10.146.10.241
    path: "/nfsshared/openloyalty/elasticsearch"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-loyalty-cache-pv0
  namespace: default
  labels:
    storage-tier: cache
spec:
  capacity:
    storage: 5Gi
  nfs:
    server: 10.146.10.241
    path: "/nfsshared/openloyalty/cache"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-loyalty-logs-pv0
  namespace: default
  labels:
    storage-tier: logs
spec:
  capacity:
    storage: 5Gi
  nfs:
    server: 10.146.10.241
    path: "/nfsshared/openloyalty/logs"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-loyalty-jwt-pv0
  namespace: default
  labels:
    storage-tier: jwt
spec:
  capacity:
    storage: 5Gi
  nfs:
    server: 10.146.10.241
    path: "/nfsshared/openloyalty/jwt"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---